//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdId { get; set; }
        public Nullable<int> AdCategory { get; set; }
        public Nullable<System.DateTime> AdDateRequest { get; set; }
        public Nullable<System.DateTime> AdDateBegin { get; set; }
        public Nullable<System.DateTime> AdDateEnd { get; set; }
        public Nullable<int> AdHeight { get; set; }
        public Nullable<int> AdWidth { get; set; }
        public int AdUserId { get; set; }
        public string AdFiles { get; set; }
        public Nullable<int> AdViews { get; set; }
        public bool AdStatus { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
