//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billboard
    {
        public int BoardId { get; set; }
        public string BoardStreet { get; set; }
        public string BoardCity { get; set; }
        public int PrecentPrice { get; set; }
    }
}
