//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelAd
    {
        public int BoardId { get; set; }
        public int AdId { get; set; }
        public int PanelLineStart { get; set; }
        public int PanelLineEnd { get; set; }
        public int PanelColumnStart { get; set; }
        public int PanelColumnEnd { get; set; }
        public System.DateTime PanelDate { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
        public virtual Billboard Billboard { get; set; }
    }
}
