//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceId { get; set; }
        public int NumsUnit { get; set; }
        public double PrecentDiscount { get; set; }
        public double Price1 { get; set; }
    }
}
